# config data for tic tac toe

welcome: Welcome to Tic Tac Toe!
explain_board: |
  In the game board below, *Y*our squares will be
     represented with 'Y's, and *C*omputer's squares
     will be represented with 'C's.
bye: Good-Bye!
request_choice: Please make your choice among %{choices}.
invalid_choice: This is not an available choice.
computer_wins: The computer has won.
human_wins: You won.
a_tie: This is a tie.
another_game?: Would you like to play again (y/n)
explain_moves: |
  Here's how to reference the squares:
     tl (top left)    | tm (top middle)    | tr (top right)
     ml (middle left) | mm (middle middle) | mr (middle right)
     bl (bottom left) | bm (bottom middle) | br (bottom right)
