# config data for tic tac toe

welcome: Welcome to Tic Tac Toe!
explain_board: |
  In the game board below, *Y*our squares will be
     represented with 'Y's, and *C*omputer's squares
     will be represented with 'C's.
explain_turntaking: A coin-toss will determine who gets to start. Computer chose heads.
explain_moves: |
  Here's how to reference the squares:
     TL (top left)    | TM (top middle)    | TR (top right)
     ML (middle left) | MM (middle middle) | MR (middle right)
     BL (bottom left) | BM (bottom middle) | BR (bottom right)
press_enter: Hit enter to toss the coin and start the game.
bye: Good-Bye!
request_choice: Please make your choice – %{choices}.
invalid_choice: This is not an available choice.
computer_begins: It's heads! The computer begins.
human_begins: It's tails! You begin.
human_chose: You chose %{move}.
computer_chose: Computer chose %{move}.
computer_wins: The computer won.
human_wins: You won.
its_a_tie: This round is a tie.
another_game?: Would you like to play again? (Y/N)
