# config data for tic tac toe

welcome: Welcome to Tic Tac Toe!
explain_board: |
  In the game board, *Y*our choices will be
     represented with 'Y's, and *C*omputer's choices
     will be represented with 'C's.
explain_moves: |
  Here's how to reference the squares:
     TL (top left)    | TM (top middle)    | TR (top right)
     ML (middle left) | MM (middle middle) | MR (middle right)
     BL (bottom left) | BM (bottom middle) | BR (bottom right)
explain_winning_conditions: The first player to win five rounds wins the game.
please_press_enter: Please press enter to continue.
want_to_begin?: Would you like to be the first player to move? (Y/N)
bye: Good-Bye!
request_choice: Please make your choice – %{choices}.
invalid_choice: This is not an available choice.
computer_begins: The computer begins.
user_begins: You begin.
user_chose: You chose %{move}.
computer_chose: Computer chose %{move}.
computer_wins: The computer won.
user_wins: You won.
its_a_tie: This round is a tie.
the current_scores_are: The current scores are %{user_score} for you and %{computer_score} for computer.
the_overall_winner_is: We have an overall winner. It's %{winner}.
another_game?: Would you like to play again? (Y/N)
